### ISSUE TITLE
Using `export * from '...'` in a page is disallowed.

### ISSUE THREAD

**Issue by joey00072** [wutali/nextjs-netlify-blog-template#22]
```
error - ./src/pages/posts/markdown-syntax.mdx:7:1
Syntax error: Using `export * from '...'` in a page is disallowed. Please use `export { default } from '...'` instead.
Read more: https://err.sh/next.js/export-all-in-page

```

No tsx file has `export * from '...' and still getting error 
I am trying to run master brach without any modification

**Comment by hstandeffer** [comment]
Yeah im having the same problem, think this repo is fairly outdated now so not sure why its still the recommended starter from netlify cms

**Comment by AylanBoscarino** [comment]
To fix this issue is possible and actually quite simple, the show answer is that you gave to update the package `next-mdx-enhanced` preferably to 5.0.0 and update the component accordingly in `src/layouts/index.tsx`.

The change in the component is needed because the package that renders mdx files has altered it's way to render components from this:

`export default function Layout(frontMatter) {
  return ({ children: content }) => {
    return (
      <div>
        <h1>{frontMatter.title}</h1>
        {content}
      </div>
    )
  }
}`

To this:
`export default function DocsPage({ children, frontMatter }) {
  return (
    <div>
      <h1>{frontMatter.title}</h1>
      {children}
    </div>
  )
}`

After this changes  you should be good to go. 😄
